# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'everyday' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for everyday

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end
pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
  'RCTText',
  'RCTWebSocket', # needed for debugging
  # Add any other subspecs you want to use in your project
]
pod 'Interactable', :path => '../node_modules/react-native-interactable'
post_install do |installer|
  `rm -rf Pods/leveldb-library/port/win`
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end